name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
   Building-Python-for-Android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8

      - name: Setting up Android SDK
        uses: android-actions/setup-android@v2

      - name: Setting up Android Tools
        uses: maxim-lobanov/setup-android-tools@v1
        with:
          packages: |
            platforms;android-27
            build-tools;28.0.2
            ndk;r23b
      - name: Setting up Python      
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        
      - name: Install Dependencies
        run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install -y build-essential ccache git zlib1g-dev python3 python3-dev libncurses5:i386 libstdc++6:i386 zlib1g:i386 openjdk-8-jdk unzip ant ccache autoconf libtool libssl-dev
        
      - name: Install Python for Android
        run: pip install python-for-android
        
      - name: Clean caches from older p4a
        run: p4a clean_all
        
      - name: Setup Python for Android
        run: p4a apk --private $HOME --package=com.ahmetkosgen.ahmet --name "Ahmet" --version 0.1 --bootstrap=sdl2 --requirements=python3,kivy
