name: Unit tests & build apps

on: ['push', 'pull_request']

steps:
  - uses: actions/checkout@v2
  - uses: nttld/setup-ndk@v1
    id: setup-ndk
    with:
      ndk-version: r21e
      add-to-path: false
  - run: ./build.sh
    env:
      ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

  - name: Set up JDK 8
  uses: actions/setup-java@v3
  with:
    java-version: 1.8

  - uses: maxim-lobanov/setup-android-tools@v1
      with:
        packages: |
          platforms;android-27

- name: Setup Android SDK
  uses: android-actions/setup-android@v2

  - name: Install dependencies
    run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install -y build-essential ccache git zlib1g-dev python3 python3-dev libncurses5:i386 libstdc++6:i386 zlib1g:i386 openjdk-8-jdk unzip ant ccache autoconf libtool libssl-dev
  
  
   
  
  
  


